<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('master_countries')->insert([
            [
                'name'=>'भारत',
                'iso2'=>'IN',
                'iso3'=>'IND',
                'phone_code'=>'+91',
                'currency'=>'INR',
                'currency_symbol'=>'₹',
                'nationality'=>'भारतीय',
                'status'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'संयुक्तराज्यअमेरिका',
                'iso2'=>'US',
                'iso3'=>'USA',
                'phone_code'=>'+1',
                'currency'=>'USD',
                'currency_symbol'=>'$',
                'nationality'=>'अमेरिकी',
                'status'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'यूनाइटेडकिंगडम',
                'iso2'=>'GB',
                'iso3'=>'GBR',
                'phone_code'=>'+44',
                'currency'=>'GBP',
                'currency_symbol'=>'£',
                'nationality'=>'ब्रिटिश',
                'status'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'कनाडा',
                'iso2'=>'CA',
                'iso3'=>'CAN',
                'phone_code'=>'+1',
                'currency'=>'CAD',
                'currency_symbol'=>'$',
                'nationality'=>'कनाडाई',
                'status'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'ऑस्ट्रेलिया',
                'iso2'=>'AU',
                'iso3'=>'AUS',
                'phone_code'=>'+61',
                'currency'=>'AUD',
                'currency_symbol'=>'$',
                'nationality'=>'ऑस्ट्रेलियाई',
                'status'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'जर्मनी',
                'iso2'=>'DE',
                'iso3'=>'DEU',
                'phone_code'=>'+49',
                'currency'=>'EUR',
                'currency_symbol'=>'€',
                'nationality'=>'जर्मन',
                'status'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'फ्रांस',
                'iso2'=>'FR',
                'iso3'=>'FRA',
                'phone_code'=>'+33',
                'currency'=>'EUR',
                'currency_symbol'=>'€',
                'nationality'=>'फ्रांसीसी',
                'status'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'जापान',
                'iso2'=>'JP',
                'iso3'=>'JPN',
                'phone_code'=>'+81',
                'currency'=>'JPY',
                'currency_symbol'=>'¥',
                'nationality'=>'जापानी',
                'status'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'चीन',
                'iso2'=>'CN',
                'iso3'=>'CHN',
                'phone_code'=>'+86',
                'currency'=>'CNY',
                'currency_symbol'=>'¥',
                'nationality'=>'चीनी',
                'status'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'name'=>'रूस',
                'iso2'=>'RU',
                'iso3'=>'RUS',
                'phone_code'=>'+7',
                'currency'=>'RUB',
                'currency_symbol'=>'₽',
                'nationality'=>'रूसी',
                'status'=>1,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
        ]);
    }
}
