<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('master_districts')->insert([
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'रायपुर',
                'district_code' => 'RP',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'दुर्ग',
                'district_code' => 'DG',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'राजनांदगांव',
                'district_code' => 'RN',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'बालोद',
                'district_code' => 'BD',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'बेमेतरा',
                'district_code' => 'BM',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'कबीरधाम',
                'district_code' => 'KD',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'धमतरी',
                'district_code' => 'DT',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'गरियाबंद',
                'district_code' => 'GB',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'महासमुंद',
                'district_code' => 'MS',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'बिलासपुर',
                'district_code' => 'BL',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'रायगढ़',
                'district_code' => 'RG',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'कोरबा',
                'district_code' => 'KB',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'जांजगीरचांपा',
                'district_code' => 'JC',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'मुंगेली',
                'district_code' => 'MG',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'गौरेला-पेंड्रा-मरवाही',
                'district_code' => 'GPM',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'सरगुजा',
                'district_code' => 'SG',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'कोरिया',
                'district_code' => 'KR',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'सूरजपुर',
                'district_code' => 'SJ',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'बलरामपुर',
                'district_code' => 'BP',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'जशपुर',
                'district_code' => 'JP',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'बलौदाबाजार',
                'district_code' => 'BB',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'सक्ती',
                'district_code' => 'SKT',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'सारंगढ़बिलाईगढ़',
                'district_code' => 'SB',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'मोहला-मानपुर-अंबागढ़चौकी',
                'district_code' => 'MMA',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'खैरागढ़-छुईखदान-गंडई',
                'district_code' => 'KCG',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'मनेंद्रगढ़-चिरमिरी-भरतपुर',
                'district_code' => 'MCB',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'कोंडागांव',
                'district_code' => 'KN',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'बस्तर',
                'district_code' => 'BS',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'दंतेवाड़ा',
                'district_code' => 'DW',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'सुकमा',
                'district_code' => 'SM',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'बीजापुर',
                'district_code' => 'BJ',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'नारायणपुर',
                'district_code' => 'NP',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'state_id' => 5,
                'name' => 'कांकेर',
                'district_code' => 'KK',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
