<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('master_states')->insert([
            [
                'country_id' => 1,
                'name' => 'आंध्रप्रदेश',
                'state_code' => 'AP',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'अरुणाचलप्रदेश',
                'state_code' => 'AR',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'असम',
                'state_code' => 'AS',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'बिहार',
                'state_code' => 'BR',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'छत्तीसगढ़',
                'state_code' => 'CG',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'गोवा',
                'state_code' => 'GA',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'गुजरात',
                'state_code' => 'GJ',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'हरियाणा',
                'state_code' => 'HR',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'हिमाचलप्रदेश',
                'state_code' => 'HP',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'झारखंड',
                'state_code' => 'JH',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'कर्नाटक',
                'state_code' => 'KA',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'केरल',
                'state_code' => 'KL',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'मध्यप्रदेश',
                'state_code' => 'MP',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'महाराष्ट्र',
                'state_code' => 'MH',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'मणिपुर',
                'state_code' => 'MN',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'मेघालय',
                'state_code' => 'ML',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'मिजोरम',
                'state_code' => 'MZ',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'नागालैंड',
                'state_code' => 'NL',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'ओडिशा',
                'state_code' => 'OD',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'पंजाब',
                'state_code' => 'PB',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'राजस्थान',
                'state_code' => 'RJ',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'सिक्किम',
                'state_code' => 'SK',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'तमिलनाडु',
                'state_code' => 'TN',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'तेलंगाना',
                'state_code' => 'TS',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'त्रिपुरा',
                'state_code' => 'TR',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'उत्तरप्रदेश',
                'state_code' => 'UP',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'उत्तराखंड',
                'state_code' => 'UK',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'country_id' => 1,
                'name' => 'पश्चिमबंगाल',
                'state_code' => 'WB',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
