import PropTypes from 'prop-types';
import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const AppPreferencesContext = createContext(null);

const translations = {
  en: {
    'app.name': 'Election Management Portal',
    'app.caption': 'Government Operations',
    'controls.language': 'Change language',
    'controls.theme': 'Change theme',
    'controls.english': 'English',
    'controls.hindi': 'Hindi',
    'controls.light': 'Light',
    'controls.dark': 'Dark',
    'customizer.title': 'Customizer',
    'customizer.themeMode': 'Theme mode',
    'customizer.accentColor': 'Accent color',
    'customizer.language': 'Language',
    'customizer.layoutDensity': 'Layout density',
    'customizer.fontSize': 'Font size',
    'customizer.reset': 'Reset preferences',
    'customizer.comfort': 'Comfort',
    'customizer.compact': 'Compact',
    'customizer.normal': 'Normal',
    'customizer.large': 'Large',
    'error.title': 'Something went wrong',
    'error.message': 'Unable to load this page. Please try again.',
    'error.reload': 'Reload page',
    'error.login': 'Go to login',
    'auth.title': 'Officer Sign In',
    'auth.subtitle': 'Access the election dashboard with your registered mobile number and OTP.',
    'auth.officialLogin': 'Official Login',
    'auth.mobileOtpLogin': 'Mobile OTP Login',
    'auth.roleBasedAccess': 'Role Based Access',
    'auth.heroTitle': 'Secure access for election officials',
    'auth.heroBody': 'Monitor voter records, polling station activity, and administrative tasks from a verified mobile login.',
    'auth.protectedSession': 'Protected session',
    'auth.protectedSessionBody': 'OTP verification helps keep election data access controlled.',
    'auth.otpIntro': 'OTP will be sent to the mobile number registered with the election office.',
    'auth.mobileLabel': 'Registered Mobile Number',
    'auth.mobilePlaceholder': 'Registered mobile number',
    'auth.passwordLabel': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.otpLabel': 'Verification OTP',
    'auth.otpPlaceholder': 'Enter 6 digit OTP',
    'auth.changeMobile': 'Change mobile number',
    'auth.resendOtp': 'Resend OTP',
    'auth.otpExpired': 'OTP expired',
    'auth.otpExpiredFull': 'OTP expired. Please resend OTP.',
    'auth.otpExpiresIn': 'OTP expires in',
    'auth.humanPending': 'Complete human verification before verifying OTP.',
    'auth.humanDone': 'Human verification complete.',
    'auth.sendOtp': 'Send OTP',
    'auth.verifyOtp': 'Verify OTP',
    'menu.dashboardOverview': 'Dashboard Overview',
    'menu.dashboard': 'Dashboard',
    'menu.electionManagement': 'Election Management',
    'menu.nagarPanchayat': 'Nagar Panchayat',
    'menu.nagariNikay': 'Nagari Nikay',
    'menu.teamAssignments': 'Team Assignments',
    'menu.reports': 'Reports',
    'menu.allocationReport': 'Allocation Report',
    'menu.dutyAnalytics': 'Duty Analytics',

    'menu.master': 'Master',
    'menu.masterCountry': 'Country Master',
    'menu.masterState': 'State Master',
    'menu.masterDistrict': 'District Master',
    'menu.masterOffice': 'Office Master',
    'menu.masterCity': 'City Master',
    'menu.masterWard': 'Ward Master',
    'menu.masterPollingStation': 'Polling Station Master',
    'menu.hrms': 'HRMS',
    'menu.masterEmployee': 'Master Employee',
    'menu.employeeType': 'Employee Type',
    'menu.designation': 'Designation',
    'menu.department': 'Department',
    'menu.payLevel': 'Pay Scale / Pay Level',
    'menu.employee': 'Employee',
    'menu.users': 'Users',
    'menu.accessManagement': 'Access Management',

    'breadcrumb.home': 'Home',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.search': 'Search',
    'common.view': 'View',
    'common.status': 'Status',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.allStatus': 'All Status',
    'common.allStates': 'All States',
    'common.allDistricts': 'All Districts',
    'common.allCities': 'All Cities',
    'common.allWards': 'All Wards',
    'common.attachment': 'Attachment',
    'common.action': 'Action',
    'common.rows': 'rows',
    'common.sno': 'S.No',
    'common.noRecords': 'No records found.',
    'common.loading': 'Loading...',
    'common.uploadLogo': 'Upload Logo Image',
    'common.existingFile': 'Existing file will remain unchanged.',
    'common.deleteConfirm': 'This record will be permanently deleted.',
    'masters.master': 'Master',
    'masters.managePrefix': 'Manage',
    'masters.manageSuffix': 'master records.',
    'masters.countries': 'Countries',
    'masters.country': 'Country',
    'masters.states': 'States',
    'masters.state': 'State',
    'masters.districts': 'Districts',
    'masters.district': 'District',
    'masters.offices': 'Offices',
    'masters.office': 'Office',
    'masters.cities': 'Cities',
    'masters.city': 'City',
    'masters.wards': 'Wards',
    'masters.ward': 'Ward',
    'masters.pollingStations': 'Polling Stations',
    'masters.pollingStation': 'Polling Station',
    'masters.employeeTypes': 'Employee Types',
    'masters.employeeType': 'Employee Type',
    'masters.designations': 'Designations',
    'masters.designation': 'Designation',
    'masters.departments': 'Departments',
    'masters.department': 'Department',
    'masters.payLevels': 'Pay Scale / Pay Levels',
    'masters.payLevel': 'Pay Scale / Pay Level',
    'masters.employees': 'Employees',
    'masters.employee': 'Employee',
    'field.name': 'Name',
    'field.code': 'Code',
    'field.country': 'Country',
    'field.state': 'State',
    'field.district': 'District',
    'field.department': 'Department',
    'field.type': 'Type',
    'field.city': 'City',
    'field.ward': 'Ward',
    'field.cityName': 'City Name',
    'field.wardNo': 'Ward No',
    'field.wardName': 'Ward Name',
    'field.pollingStationName': 'Polling Station Name',
    'field.officeCode': 'Office Code',
    'field.officeName': 'Office Name',
    'field.officeType': 'Office Type',
    'field.parentOfficeId': 'Parent Office ID',
    'field.countryName': 'Country Name',
    'field.stateName': 'State Name',
    'field.districtName': 'District Name',
    'field.districtCode': 'District Code',
    'field.minAmountPay': 'Min Amount Pay',
    'field.maxAmountPay': 'Max Amount Pay',
    'field.karyalayName': 'Karyalay Name',
    'data.headOffice': 'Head Office',
    'data.branchOffice': 'Branch Office',
    'data.normal': 'Normal',
    'data.review': 'Review',
    'data.attention': 'Attention',
    'data.verified': 'Verified',
    'data.pending': 'Pending',
    'data.correction': 'Correction',
    'data.rejected': 'Rejected',
    'dashboard.liveControlRoom': 'Live Election Control Room',
    'dashboard.title': 'District Election Dashboard',
    'dashboard.subtitle': 'Monitor voter services, booth readiness, polling activity, and field incidents from one official workspace.',
    'dashboard.registeredVoters': 'Registered Voters',
    'dashboard.registeredVotersCaption': 'Across 8 constituencies',
    'dashboard.pollingStations': 'Polling Stations',
    'dashboard.pollingStationsCaption': '1,219 ready for polling',
    'dashboard.todayTurnout': 'Today Turnout',
    'dashboard.todayTurnoutCaption': '+7.4% since last update',
    'dashboard.openIncidents': 'Open Incidents',
    'dashboard.openIncidentsCaption': '4 marked high priority',
    'dashboard.turnoutGraph': 'Constituency Turnout Bar Graph',
    'dashboard.voterPieChart': 'Voter Verification Pie Chart',
    'dashboard.monitoring': 'Constituency Monitoring',
    'dashboard.constituency': 'Constituency',
    'dashboard.booths': 'Booths',
    'dashboard.officers': 'Officers',
    'dashboard.turnout': 'Turnout',
    'dashboard.status': 'Status',
    'dashboard.current': 'Current',
    'dashboard.operationsReadiness': 'Operations Readiness',
    'dashboard.priorityTasks': 'Priority Tasks',
    'dashboard.quickInsights': 'Quick Insights',
    'dashboard.serviceDesk': 'Service Desk',
    'dashboard.pollingTeam': 'Polling Team',
    'dashboard.lastUpdated': 'Last updated',
    'dashboard.boothChecklists': 'Booth checklists completed',
    'dashboard.securityCompliance': 'Strong room security compliance',
    'dashboard.fieldUpdateInterval': 'Average field update interval',
    'dashboard.verificationQueue': 'Voter verification queue',
    'dashboard.evmReadiness': 'EVM/VVPAT readiness',
    'dashboard.officerAttendance': 'Officer attendance',
    'dashboard.task1': 'Approve pending booth officer replacements',
    'dashboard.task2': 'Review high-priority incident reports',
    'dashboard.task3': 'Publish 4 PM turnout bulletin',
    'dashboard.task4': 'Validate strong room security checklist',
    'dashboard.helpdeskCalls': 'Helpdesk calls resolved',
    'dashboard.formsProcessed': 'Forms processed today',
    'dashboard.teamsDeployed': 'Teams deployed',
    'dashboard.materialKits': 'Material kits ready',

    // User Access Management
    'access.title': 'Access Management',
    'access.subtitle': 'Create users and assign state, district and office access.',
    'access.createUser': 'Create User',
    'access.userRecords': 'User Records',
    'access.user': 'User',
    'access.userId': 'User ID',
    'access.mobile': 'Mobile Number',
    'access.role': 'Role',
    'access.permissions': 'Permissions',
    'access.reset': 'Reset',
    'access.resetPassword': 'Reset Password',
    'access.deleteUser': 'Delete User',
    'access.confirmReset': 'Are you sure you want to reset the password for this user?',
    'access.confirmDelete': 'This user and access permissions will be deleted.',
    'access.stateAccess': 'State Access',
    'access.countryAccess': 'Country Access',
    'access.districtAccess': 'District Access',
    'access.officeAccess': 'Office Access',
    'access.dragHere': 'Drag items here',
    'access.noRecords': 'No available records.',
    'access.errCountryFirst': 'Please select the related Country first.',
    'access.errStateMismatch': 'Selected State does not belong to the chosen Country. Please select the correct hierarchy.',
    'access.errStateFirst': 'Please select the related State first.',
    'access.errDistrictMismatch': 'Selected District does not belong to the chosen State. Please select the correct hierarchy.',
    'access.errAdminState': 'Please assign at least one State for System Admin.',
    'access.saveAccess': 'Save Access',
    'access.sysAdminNote': 'System Admin is state-scoped. Please assign one or more states only.',
    'access.fullName': 'Full Name',
    'access.email': 'Email Address',
    'access.tempPassword': 'Temporary Password',
    'access.selectCountry': 'Select Country',
    'access.selectState': 'Select State',
    'access.selectDistrict': 'Select District',
    'access.noOffice': 'No Office',
    'access.address': 'Address',
    'access.saveUser': 'Save User',

    // Reports & Analytics
    'reports.allocationTitle': 'Allocation Report',
    'reports.allocationSubtitle': 'Filter, verify, and export official duty orders and deployment lists.',
    'reports.exportCsv': 'Export CSV',
    'reports.printRoster': 'Print Roster',
    'reports.searchPlaceholder': 'Search Booth / Officer...',
    'reports.activeAssignments': 'Active Assignments List',
    'reports.officerName': 'Officer Name',
    'reports.employeeId': 'Employee ID',
    'reports.stationDeployed': 'Station Deployed',
    'reports.department': 'Department',
    'reports.contact': 'Contact',
    'reports.noAllocations': 'No allocations found.',

    'analytics.title': 'Duty Analytics',
    'analytics.subtitle': 'Visual metrics, deployment rates, exemption statuses, and department contribution stats.',
    'analytics.staffPool': 'Total Staff Pool',
    'analytics.activeDeployments': 'Active Deployments',
    'analytics.exemptedStaff': 'Exempted Staff',
    'analytics.exemptionAppeals': 'Exemption Appeals',
    'analytics.deptRatios': 'Department Deployment Ratios',
    'analytics.roleStats': 'Role Distribution Statistics',
    'analytics.proDeployed': 'Presiding Officers (PRO) Deployed',
    'analytics.po1Deployed': 'Polling Officers 1 (PO1) Deployed',
    'analytics.po2Deployed': 'Polling Officers 2 (PO2) Deployed',
    'analytics.moDeployed': 'Micro Observers (MO) Deployed',

    // Election Dashboard
    'election.npTitle': 'Nagar Panchayat Dashboard',
    'election.rnTitle': 'Nagari Nikay Dashboard',
    'election.npSubtitle': 'Monitor constituency stats, wards, polling booths, and manage sequential scheduling for local Nagar Panchayat elections.',
    'election.rnSubtitle': 'Monitor constituency stats, wards, polling booths, and manage sequential scheduling for local Nagari Nikay elections.',
    'election.selectNpCity': 'Select Nagar Panchayat City',
    'election.selectRnCity': 'Select Nagari Nikay City',
    'election.allNpCities': 'All Nagar Panchayat Cities',
    'election.allRnCities': 'All Nagari Nikay Cities',
    'election.chooseCity': 'Choose a city...',
    'election.createSchedule': 'Create Team Scheduled',
    'election.notAssigned': 'Not Assigned',
    'election.wardsScheduled': 'Wards Scheduled',
    'election.boothsScheduled': 'Booths Scheduled',
    'election.teamsGenerated': 'Teams Generated',
    'election.deployedOfficers': 'Deployed Officers',
    'election.applyDuty': 'Apply Duty',
    'election.dutyCriteria': 'Apply Duty Criteria',
    'election.dob': 'Date of Birth',
    'election.genderCond': 'Gender Condition',
    'election.any': 'Any',
    'election.male': 'Male',
    'election.female': 'Female',
    'election.teamAssignments': 'Polling Team Assignments',
    'election.zonesOverview': 'Constituency Zones Overview',
    'election.timeline': 'Election Timeline Details',
    'election.nominationStage': 'Nomination Stage',
    'election.verificationChecks': 'Verification Checks',
    'election.securityDeployed': 'Security Staff Deployed',
    'election.pollingDate': 'Polling Date',
    'election.open': 'Open',
    'election.active': 'Active',
    'election.yes': 'Yes',
    'election.no': 'No',
    'election.selectMonitor': 'Please select a city to monitor its dashboard.',
    'election.exemptTitle': 'Exempt Employee from Assignments',
    'election.exemptBtn': 'Exempt Employee',
    'election.searchTeam': 'Search Team ID',
    'election.searchEmp': 'Search Employee ID/Code',
    'election.searchIntro': 'Search by Team ID or Employee ID/Code. City selection is optional.',
    'election.teamId': 'Team ID',
    'election.stationWard': 'Polling Station / Ward',
    'election.noTeamRecord': 'Is Team ID ka record nahi mila.',
    'election.assignMembers': 'Assign Team Members',
    'election.searchEmpPlaceholder': 'Type to search employee name or code...',
    'election.saveAssignments': 'Save Assignments',
    'election.nominationsVerification': 'Nominations verification',
    'election.localCandidates': 'Local candidates checklist validation',
    'election.boothSecurity': 'Polling Booth security',
    'election.boothSecurityDeployment': 'Deployment of security personnel check for booths',
    'election.evmConfig': 'EVM configuration',
    'election.boothTestingLogs': 'Booth allocation and testing logs verification',
    'election.enterEmpId': 'Please enter Employee ID or Code.',
    'election.exemptSuccess': 'Employee exempted successfully.',
    'election.exemptFailed': 'Failed to exempt employee.',
    'election.saveSuccess': 'Assignments saved successfully.',
    'election.saveFailed': 'Failed to save assignments.',
    'election.searchTeamPlaceholder': 'Example: 0001, 0002 or 1, 2',
    'election.searchEmpPlaceholder2': 'Example: NIC001 or 123',
    'election.searchEmpPlaceholderExempt': 'Enter employee id or code (e.g. NIC001)'
  },
  hi: {
    'app.name': 'निर्वाचन प्रबंधन पोर्टल',
    'app.caption': 'सरकारी संचालन',
    'controls.language': 'भाषा बदलें',
    'controls.theme': 'थीम बदलें',
    'controls.english': 'English',
    'controls.hindi': 'हिन्दी',
    'controls.light': 'लाइट',
    'controls.dark': 'डार्क',
    'customizer.title': 'कस्टमाइज़र',
    'customizer.themeMode': 'थीम मोड',
    'customizer.accentColor': 'एक्सेंट रंग',
    'customizer.language': 'भाषा',
    'customizer.layoutDensity': 'लेआउट घनत्व',
    'customizer.fontSize': 'फ़ॉन्ट आकार',
    'customizer.reset': 'रीसेट करें',
    'customizer.comfort': 'आरामदायक',
    'customizer.compact': 'कॉम्पैक्ट',
    'customizer.normal': 'सामान्य',
    'customizer.large': 'बड़ा',
    'error.title': 'कुछ समस्या हुई',
    'error.message': 'यह पेज लोड नहीं हो पाया। कृपया फिर प्रयास करें।',
    'error.reload': 'पेज फिर लोड करें',
    'error.login': 'लॉगिन पर जाएं',
    'auth.title': 'अधिकारी लॉगिन',
    'auth.subtitle': 'पंजीकृत मोबाइल नंबर और OTP से निर्वाचन डैशबोर्ड खोलें।',
    'auth.officialLogin': 'आधिकारिक लॉगिन',
    'auth.mobileOtpLogin': 'मोबाइल OTP लॉगिन',
    'auth.roleBasedAccess': 'भूमिका आधारित पहुंच',
    'auth.heroTitle': 'निर्वाचन अधिकारियों के लिए सुरक्षित पहुंच',
    'auth.heroBody': 'सत्यापित मोबाइल लॉगिन से मतदाता रिकॉर्ड, मतदान केंद्र गतिविधि और प्रशासनिक कार्य देखें।',
    'auth.protectedSession': 'सुरक्षित सत्र',
    'auth.protectedSessionBody': 'OTP सत्यापन निर्वाचन डेटा की पहुंच नियंत्रित रखता है।',
    'auth.otpIntro': 'OTP निर्वाचन कार्यालय में पंजीकृत मोबाइल नंबर पर भेजा जाएगा।',
    'auth.mobileLabel': 'पंजीकृत मोबाइल नंबर',
    'auth.mobilePlaceholder': 'पंजीकृत मोबाइल नंबर',
    'auth.passwordLabel': 'पासवर्ड',
    'auth.passwordPlaceholder': 'अपना पासवर्ड दर्ज करें',
    'auth.otpLabel': 'सत्यापन OTP',
    'auth.otpPlaceholder': '6 अंकों का OTP दर्ज करें',
    'auth.changeMobile': 'मोबाइल नंबर बदलें',
    'auth.resendOtp': 'OTP फिर भेजें',
    'auth.otpExpired': 'OTP समाप्त',
    'auth.otpExpiredFull': 'OTP समाप्त हो गया है। कृपया फिर से OTP भेजें।',
    'auth.otpExpiresIn': 'OTP समाप्त होगा',
    'auth.humanPending': 'OTP सत्यापित करने से पहले मानव सत्यापन पूरा करें।',
    'auth.humanDone': 'मानव सत्यापन पूरा हुआ।',
    'auth.sendOtp': 'OTP भेजें',
    'auth.verifyOtp': 'OTP सत्यापित करें',
    'menu.dashboardOverview': 'डैशबोर्ड अवलोकन',
    'menu.dashboard': 'डैशबोर्ड',
    'menu.electionManagement': 'निर्वाचन प्रबंधन',
    'menu.nagarPanchayat': 'नगर पंचायत',
    'menu.nagariNikay': 'नगरीय निकाय',
    'menu.teamAssignments': 'टीम असाइनमेंट',
    'menu.reports': 'रिपोर्ट',
    'menu.allocationReport': 'आवंटन रिपोर्ट',
    'menu.dutyAnalytics': 'ड्यूटी एनालिटिक्स',

    'menu.master': 'मास्टर',
    'menu.masterCountry': 'देश मास्टर',
    'menu.masterState': 'राज्य मास्टर',
    'menu.masterDistrict': 'जिला मास्टर',
    'menu.masterOffice': 'कार्यालय मास्टर',
    'menu.masterCity': 'शहर मास्टर',
    'menu.masterWard': 'वार्ड मास्टर',
    'menu.masterPollingStation': 'मतदान केंद्र मास्टर',
    'menu.hrms': 'एचआरएमएस',
    'menu.masterEmployee': 'कर्मचारी मास्टर',
    'menu.employeeType': 'कर्मचारी प्रकार',
    'menu.designation': 'पदनाम',
    'menu.department': 'विभाग',
    'menu.payLevel': 'वेतनमान / वेतन स्तर',
    'menu.employee': 'कर्मचारी',
    'menu.users': 'उपयोगकर्ता',
    'menu.accessManagement': 'एक्सेस प्रबंधन',

    'breadcrumb.home': 'होम',
    'common.create': 'बनाएं',
    'common.update': 'अपडेट',
    'common.save': 'सेव',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएं',
    'common.search': 'खोजें',
    'common.view': 'देखें',
    'common.status': 'स्थिति',
    'common.active': 'सक्रिय',
    'common.inactive': 'निष्क्रिय',
    'common.allStatus': 'सभी स्थिति',
    'common.allStates': 'सभी राज्य',
    'common.allDistricts': 'सभी जिले',
    'common.allCities': 'सभी शहर',
    'common.allWards': 'सभी वार्ड',
    'common.attachment': 'अटैचमेंट',
    'common.action': 'कार्यवाही',
    'common.rows': 'पंक्तियां',
    'common.sno': 'क्र.सं.',
    'common.noRecords': 'कोई रिकॉर्ड नहीं मिला।',
    'common.loading': 'लोड हो रहा है...',
    'common.uploadLogo': 'लोगो इमेज अपलोड करें',
    'common.existingFile': 'मौजूदा फ़ाइल वही रहेगी।',
    'common.deleteConfirm': 'यह रिकॉर्ड स्थायी रूप से हटाया जाएगा।',
    'masters.master': 'मास्टर',
    'masters.managePrefix': 'प्रबंधित करें',
    'masters.manageSuffix': 'मास्टर रिकॉर्ड।',
    'masters.countries': 'देश',
    'masters.country': 'देश',
    'masters.states': 'राज्य',
    'masters.state': 'राज्य',
    'masters.districts': 'जिले',
    'masters.district': 'जिला',
    'masters.offices': 'कार्यालय',
    'masters.office': 'कार्यालय',
    'masters.cities': 'शहर',
    'masters.city': 'शहर',
    'masters.wards': 'वार्ड',
    'masters.ward': 'वार्ड',
    'masters.pollingStations': 'मतदान केंद्र',
    'masters.pollingStation': 'मतदान केंद्र',
    'masters.employeeTypes': 'कर्मचारी प्रकार',
    'masters.employeeType': 'कर्मचारी प्रकार',
    'masters.designations': 'पदनाम',
    'masters.designation': 'पदनाम',
    'masters.departments': 'विभाग',
    'masters.department': 'विभाग',
    'masters.payLevels': 'वेतनमान / वेतन स्तर',
    'masters.payLevel': 'वेतनमान / वेतन स्तर',
    'masters.employees': 'कर्मचारी',
    'masters.employee': 'कर्मचारी',
    'field.name': 'नाम',
    'field.code': 'कोड',
    'field.country': 'देश',
    'field.state': 'राज्य',
    'field.district': 'जिला',
    'field.department': 'विभाग',
    'field.type': 'प्रकार',
    'field.city': 'शहर',
    'field.ward': 'वार्ड',
    'field.cityName': 'शहर का नाम',
    'field.wardNo': 'वार्ड नंबर',
    'field.wardName': 'वार्ड का नाम',
    'field.pollingStationName': 'मतदान केंद्र का नाम',
    'field.officeCode': 'कार्यालय कोड',
    'field.officeName': 'कार्यालय नाम',
    'field.officeType': 'कार्यालय प्रकार',
    'field.parentOfficeId': 'मुख्य कार्यालय ID',
    'field.countryName': 'देश का नाम',
    'field.stateName': 'राज्य का नाम',
    'field.districtName': 'जिले का नाम',
    'field.districtCode': 'जिला कोड',
    'field.minAmountPay': 'न्यूनतम राशि भुगतान',
    'field.maxAmountPay': 'अधिकतम राशि भुगतान',
    'field.karyalayName': 'कार्यालय नाम',
    'data.headOffice': 'मुख्य कार्यालय',
    'data.branchOffice': 'शाखा कार्यालय',
    'data.normal': 'सामान्य',
    'data.review': 'समीक्षा',
    'data.attention': 'ध्यान दें',
    'data.verified': 'सत्यापित',
    'data.pending': 'लंबित',
    'data.correction': 'सुधार',
    'data.rejected': 'अस्वीकृत',
    'dashboard.liveControlRoom': 'लाइव निर्वाचन नियंत्रण कक्ष',
    'dashboard.title': 'जिला निर्वाचन डैशबोर्ड',
    'dashboard.subtitle': 'मतदाता सेवाएं, बूथ तैयारी, मतदान गतिविधि और फील्ड घटनाएं एक आधिकारिक कार्यक्षेत्र से देखें।',
    'dashboard.registeredVoters': 'पंजीकृत मतदाता',
    'dashboard.registeredVotersCaption': '8 निर्वाचन क्षेत्रों में',
    'dashboard.pollingStations': 'मतदान केंद्र',
    'dashboard.pollingStationsCaption': '1,219 मतदान के लिए तैयार',
    'dashboard.todayTurnout': 'आज का मतदान',
    'dashboard.todayTurnoutCaption': 'पिछले अपडेट से +7.4%',
    'dashboard.openIncidents': 'खुली घटनाएं',
    'dashboard.openIncidentsCaption': '4 उच्च प्राथमिकता में चिह्नित',
    'dashboard.turnoutGraph': 'निर्वाचन क्षेत्र मतदान बार ग्राफ',
    'dashboard.voterPieChart': 'मतदाता सत्यापन पाई चार्ट',
    'dashboard.monitoring': 'निर्वाचन क्षेत्र निगरानी',
    'dashboard.constituency': 'निर्वाचन क्षेत्र',
    'dashboard.booths': 'बूथ',
    'dashboard.officers': 'अधिकारी',
    'dashboard.turnout': 'मतदान',
    'dashboard.status': 'स्थिति',
    'dashboard.current': 'वर्तमान',
    'dashboard.operationsReadiness': 'संचालन तैयारी',
    'dashboard.priorityTasks': 'प्राथमिक कार्य',
    'dashboard.quickInsights': 'त्वरित जानकारी',
    'dashboard.serviceDesk': 'सेवा डेस्क',
    'dashboard.pollingTeam': 'मतदान टीम',
    'dashboard.lastUpdated': 'अंतिम अपडेट',
    'dashboard.boothChecklists': 'बूथ चेकलिस्ट पूरी',
    'dashboard.securityCompliance': 'स्ट्रॉन्ग रूम सुरक्षा अनुपालन',
    'dashboard.fieldUpdateInterval': 'औसत फील्ड अपडेट अंतराल',
    'dashboard.verificationQueue': 'मतदाता सत्यापन कतार',
    'dashboard.evmReadiness': 'EVM/VVPAT तैयारी',
    'dashboard.officerAttendance': 'अधिकारी उपस्थिति',
    'dashboard.task1': 'लंबित बूथ अधिकारी बदलाव स्वीकृत करें',
    'dashboard.task2': 'उच्च प्राथमिकता घटना रिपोर्ट की समीक्षा करें',
    'dashboard.task3': '4 PM मतदान बुलेटिन प्रकाशित करें',
    'dashboard.task4': 'स्ट्रॉन्ग रूम सुरक्षा चेकलिस्ट सत्यापित करें',
    'dashboard.helpdeskCalls': 'हेल्पडेस्क कॉल समाधान',
    'dashboard.formsProcessed': 'आज प्रोसेस किए गए फॉर्म',
    'dashboard.teamsDeployed': 'तैनात टीमें',
    'dashboard.materialKits': 'तैयार सामग्री किट',

    // User Access Management
    'access.title': 'एक्सेस प्रबंधन',
    'access.subtitle': 'उपयोगकर्ता बनाएं और राज्य, जिला और कार्यालय की अनुमति असाइन करें।',
    'access.createUser': 'उपयोगकर्ता बनाएं',
    'access.userRecords': 'उपयोगकर्ता रिकॉर्ड',
    'access.user': 'उपयोगकर्ता',
    'access.userId': 'उपयोगकर्ता आईडी',
    'access.mobile': 'मोबाइल नंबर',
    'access.role': 'भूमिका',
    'access.permissions': 'अनुमतियां',
    'access.reset': 'रीसेट',
    'access.resetPassword': 'पासवर्ड रीसेट',
    'access.deleteUser': 'उपयोगकर्ता हटाएं',
    'access.confirmReset': 'क्या आप वाकई इस उपयोगकर्ता का पासवर्ड रीसेट करना चाहते हैं?',
    'access.confirmDelete': 'यह उपयोगकर्ता और पहुंच अनुमतियां हटा दी जाएंगी।',
    'access.stateAccess': 'राज्य पहुंच',
    'access.countryAccess': 'देश पहुंच',
    'access.districtAccess': 'जिला पहुंच',
    'access.officeAccess': 'कार्यालय पहुंच',
    'access.dragHere': 'आइटम को यहां खींचें',
    'access.noRecords': 'कोई उपलब्ध रिकॉर्ड नहीं।',
    'access.errCountryFirst': 'कृपया पहले संबंधित देश का चयन करें।',
    'access.errStateMismatch': 'चयनित राज्य चुने गए देश के अंतर्गत नहीं आता है। कृपया सही पदानुक्रम चुनें।',
    'access.errStateFirst': 'कृपया पहले संबंधित राज्य का चयन करें।',
    'access.errDistrictMismatch': 'चयनित जिला चुने गए राज्य के अंतर्गत नहीं आता है। कृपया सही पदानुक्रम चुनें।',
    'access.errAdminState': 'कृपया सिस्टम एडमिन के लिए कम से कम एक राज्य असाइन करें।',
    'access.saveAccess': 'एक्सेस सहेजें',
    'access.sysAdminNote': 'सिस्टम एडमिन राज्य-स्तरीय है। कृपया केवल एक या अधिक राज्य असाइन करें।',
    'access.fullName': 'पूरा नाम',
    'access.email': 'ईमेल पता',
    'access.tempPassword': 'अस्थायी पासवर्ड',
    'access.selectCountry': 'देश चुनें',
    'access.selectState': 'राज्य चुनें',
    'access.selectDistrict': 'जिला चुनें',
    'access.noOffice': 'कोई कार्यालय नहीं',
    'access.address': 'पता',
    'access.saveUser': 'उपयोगकर्ता सहेजें',

    // Reports & Analytics
    'reports.allocationTitle': 'आवंटन रिपोर्ट',
    'reports.allocationSubtitle': 'आधिकारिक ड्यूटी आदेश और तैनाती सूचियों को फ़िल्टर, सत्यापित और निर्यात करें।',
    'reports.exportCsv': 'CSV निर्यात करें',
    'reports.printRoster': 'रोस्टर प्रिंट करें',
    'reports.searchPlaceholder': 'बूथ या अधिकारी खोजें...',
    'reports.activeAssignments': 'सक्रिय असाइनमेंट सूची',
    'reports.officerName': 'अधिकारी का नाम',
    'reports.employeeId': 'कर्मचारी आईडी',
    'reports.stationDeployed': 'तैनात केंद्र',
    'reports.department': 'विभाग',
    'reports.contact': 'संपर्क',
    'reports.noAllocations': 'कोई आवंटन नहीं मिला।',

    'analytics.title': 'ड्यूटी एनालिटिक्स',
    'analytics.subtitle': 'दृश्य मेट्रिक्स, तैनाती दरें, छूट की स्थिति और विभाग योगदान आँकड़े।',
    'analytics.staffPool': 'कुल स्टाफ पूल',
    'analytics.activeDeployments': 'सक्रिय तैनाती',
    'analytics.exemptedStaff': 'छूट प्राप्त स्टाफ',
    'analytics.exemptionAppeals': 'छूट अपीलें',
    'analytics.deptRatios': 'विभाग तैनाती अनुपात',
    'analytics.roleStats': 'भूमिका वितरण आँकड़े',
    'analytics.proDeployed': 'पीठासीन अधिकारी (PRO) तैनात',
    'analytics.po1Deployed': 'मतदान अधिकारी 1 (PO1) तैनात',
    'analytics.po2Deployed': 'मतदान अधिकारी 2 (PO2) तैनात',
    'analytics.moDeployed': 'माइक्रो ऑब्जर्वर (MO) तैनात',

    // Election Dashboard
    'election.npTitle': 'नगर पंचायत डैशबोर्ड',
    'election.rnTitle': 'नगरीय निकाय डैशबोर्ड',
    'election.npSubtitle': 'निर्वाचन क्षेत्र के आंकड़े, वार्ड, मतदान केंद्रों की निगरानी करें और स्थानीय नगर पंचायत चुनावों के लिए अनुक्रमिक समय-सारिणी प्रबंधित करें।',
    'election.rnSubtitle': 'निर्वाचन क्षेत्र के आंकड़े, वार्ड, मतदान केंद्रों की निगरानी करें और स्थानीय नगरीय निकाय चुनावों के लिए अनुक्रमिक समय-सारिणी प्रबंधित करें।',
    'election.selectNpCity': 'नगर पंचायत शहर चुनें',
    'election.selectRnCity': 'नगरीय निकाय शहर चुनें',
    'election.allNpCities': 'सभी नगर पंचायत शहर',
    'election.allRnCities': 'सभी नगरीय निकाय शहर',
    'election.chooseCity': 'शहर चुनें...',
    'election.createSchedule': 'टीम शेड्यूलिंग बनाएं',
    'election.notAssigned': 'आवंटित नहीं',
    'election.wardsScheduled': 'अनुसूचित वार्ड',
    'election.boothsScheduled': 'अनुसूचित बूथ',
    'election.teamsGenerated': 'उत्पन्न टीमें',
    'election.deployedOfficers': 'तैनात अधिकारी',
    'election.applyDuty': 'ड्यूटी लागू करें',
    'election.dutyCriteria': 'ड्यूटी मानदंड लागू करें',
    'election.dob': 'जन्म तिथि',
    'election.genderCond': 'जेंडर शर्त',
    'election.any': 'कोई भी',
    'election.male': 'पुरुष',
    'election.female': 'महिला',
    'election.teamAssignments': 'मतदान टीम असाइनमेंट',
    'election.zonesOverview': 'निर्वाचन क्षेत्र क्षेत्र अवलोकन',
    'election.timeline': 'चुनाव समयरेखा विवरण',
    'election.nominationStage': 'नामांकन चरण',
    'election.verificationChecks': 'सत्यापन जाँच',
    'election.securityDeployed': 'सुरक्षा कर्मचारी तैनात',
    'election.pollingDate': 'मतदान तिथि',
    'election.open': 'खुला',
    'election.active': 'सक्रिय',
    'election.yes': 'हाँ',
    'election.no': 'नहीं',
    'election.selectMonitor': 'डैशबोर्ड देखने के लिए कृपया एक शहर का चयन करें।',
    'election.exemptTitle': 'असाइनमेंट से कर्मचारी को छूट दें',
    'election.exemptBtn': 'छूट दें',
    'election.searchTeam': 'टीम आईडी खोजें',
    'election.searchEmp': 'कर्मचारी आईडी/कोड खोजें',
    'election.searchIntro': 'टीम आईडी या कर्मचारी आईडी/कोड द्वारा खोजें। शहर का चयन वैकल्पिक है।',
    'election.teamId': 'टीम आईडी',
    'election.stationWard': 'मतदान केंद्र / वार्ड',
    'election.noTeamRecord': 'इस टीम आईडी का कोई रिकॉर्ड नहीं मिला।',
    'election.assignMembers': 'टीम के सदस्य असाइन करें',
    'election.searchEmpPlaceholder': 'कर्मचारी का नाम या कोड खोजने के लिए टाइप करें...',
    'election.saveAssignments': 'असाइनमेंट सहेजें',
    'election.nominationsVerification': 'नामांकन सत्यापन',
    'election.localCandidates': 'स्थानीय उम्मीदवारों की चेकलिस्ट का सत्यापन',
    'election.boothSecurity': 'मतदान केंद्र सुरक्षा',
    'election.boothSecurityDeployment': 'मतदान केंद्रों के लिए सुरक्षा कर्मियों की तैनाती की जाँच',
    'election.evmConfig': 'ईवीएम कॉन्फ़िगरेशन',
    'election.boothTestingLogs': 'बूथ आवंटन और परीक्षण लॉग का सत्यापन',
    'election.enterEmpId': 'कृपया कर्मचारी आईडी या कोड दर्ज करें।',
    'election.exemptSuccess': 'कर्मचारी को सफलतापूर्वक छूट दी गई।',
    'election.exemptFailed': 'कर्मचारी को छूट देने में विफल।',
    'election.saveSuccess': 'असाइनमेंट सफलतापूर्वक सहेजे गए।',
    'election.saveFailed': 'असाइनमेंट सहेजने में विफल।',
    'election.searchTeamPlaceholder': 'उदाहरण: 0001, 0002 या 1, 2',
    'election.searchEmpPlaceholder2': 'उदाहरण: NIC001 या 123',
    'election.searchEmpPlaceholderExempt': 'कर्मचारी आईडी या कोड दर्ज करें (जैसे NIC001)'
  }
};

const labelKey = (value) =>
  `field.${String(value)
    .replace(/[^a-zA-Z0-9 ]/g, '')
    .replace(/\s+([a-zA-Z0-9])/g, (_, chr) => chr.toUpperCase())
    .replace(/^./, (chr) => chr.toLowerCase())}`;

const getStoredValue = (key, fallback) => {
  if (typeof window === 'undefined') return fallback;

  return localStorage.getItem(key) || fallback;
};

export function AppPreferencesProvider({ children }) {
  const [language, setLanguageState] = useState(() => getStoredValue('app_language', 'hi'));
  const [themeMode, setThemeModeState] = useState(() => getStoredValue('app_theme_mode', 'light'));
  const [accentColor, setAccentColorState] = useState(() => getStoredValue('app_accent_color', 'indigo'));
  const [layoutDensity, setLayoutDensityState] = useState(() => getStoredValue('app_layout_density', 'comfortable'));
  const [fontScale, setFontScaleState] = useState(() => getStoredValue('app_font_scale', 'normal'));

  useEffect(() => {
    document.documentElement.lang = language === 'hi' ? 'hi' : 'en';
  }, [language]);

  const setLanguage = (nextLanguage) => {
    setLanguageState(nextLanguage);
    localStorage.setItem('app_language', nextLanguage);
  };

  const setThemeMode = (nextThemeMode) => {
    setThemeModeState(nextThemeMode);
    localStorage.setItem('app_theme_mode', nextThemeMode);
  };

  const setAccentColor = (nextAccentColor) => {
    setAccentColorState(nextAccentColor);
    localStorage.setItem('app_accent_color', nextAccentColor);
  };

  const setLayoutDensity = (nextLayoutDensity) => {
    setLayoutDensityState(nextLayoutDensity);
    localStorage.setItem('app_layout_density', nextLayoutDensity);
  };

  const setFontScale = (nextFontScale) => {
    setFontScaleState(nextFontScale);
    localStorage.setItem('app_font_scale', nextFontScale);
  };

  const resetPreferences = () => {
    setLanguage('hi');
    setThemeMode('light');
    setAccentColor('indigo');
    setLayoutDensity('comfortable');
    setFontScale('normal');
  };

  const t = (key) => translations[language]?.[key] || translations.en[key] || key;
  const tl = (value) => {
    const key = labelKey(value);
    const translated = t(key);

    return translated === key ? value : translated;
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t,
      tl,
      themeMode,
      setThemeMode,
      accentColor,
      setAccentColor,
      layoutDensity,
      setLayoutDensity,
      fontScale,
      setFontScale,
      resetPreferences
    }),
    [language, themeMode, accentColor, layoutDensity, fontScale]
  );

  return <AppPreferencesContext.Provider value={value}>{children}</AppPreferencesContext.Provider>;
}

AppPreferencesProvider.propTypes = { children: PropTypes.node };

export function useAppPreferences() {
  const context = useContext(AppPreferencesContext);

  if (!context) {
    throw new Error('useAppPreferences must be used inside AppPreferencesProvider');
  }

  return context;
}
