const hiOverrides: Record<string, string> = {
  'app.name': 'निर्वाचन प्रबंधन पोर्टल',
  'app.caption': 'सरकारी संचालन',
  'controls.language': 'भाषा बदलें',
  'controls.theme': 'थीम बदलें',
  'controls.english': 'अंग्रेजी',
  'controls.hindi': 'हिन्दी',
  'controls.light': 'लाइट',
  'controls.dark': 'डार्क',
  'customizer.title': 'कस्टमाइजर',
  'customizer.themeMode': 'थीम मोड',
  'customizer.accentColor': 'एक्सेंट रंग',
  'customizer.language': 'भाषा',
  'customizer.layoutDensity': 'लेआउट घनत्व',
  'customizer.fontSize': 'फॉन्ट आकार',
  'customizer.reset': 'रीसेट करें',
  'customizer.comfort': 'आरामदायक',
  'customizer.compact': 'कॉम्पैक्ट',
  'customizer.normal': 'सामान्य',
  'customizer.large': 'बड़ा',
  'error.title': 'कुछ समस्या हुई',
  'error.message': 'यह पेज लोड नहीं हो पाया। कृपया फिर प्रयास करें।',
  'error.reload': 'पेज फिर लोड करें',
  'error.login': 'लॉगिन पर जाएं',
  'auth.title': 'अधिकारी लॉगिन',
  'auth.subtitle': 'पंजीकृत मोबाइल नंबर और ओटीपी से निर्वाचन डैशबोर्ड खोलें।',
  'auth.officialLogin': 'आधिकारिक लॉगिन',
  'auth.mobileOtpLogin': 'मोबाइल ओटीपी लॉगिन',
  'auth.roleBasedAccess': 'भूमिका आधारित पहुंच',
  'auth.heroTitle': 'निर्वाचन अधिकारियों के लिए सुरक्षित पहुंच',
  'auth.heroBody': 'सत्यापित मोबाइल लॉगिन से मतदाता रिकॉर्ड, मतदान केंद्र गतिविधि और प्रशासनिक कार्य देखें।',
  'auth.protectedSession': 'सुरक्षित सत्र',
  'auth.protectedSessionBody': 'ओटीपी सत्यापन निर्वाचन डेटा की पहुंच नियंत्रित रखता है।',
  'auth.otpIntro': 'ओटीपी निर्वाचन कार्यालय में पंजीकृत मोबाइल नंबर पर भेजा जाएगा।',
  'auth.mobileLabel': 'पंजीकृत मोबाइल नंबर',
  'auth.mobilePlaceholder': 'पंजीकृत मोबाइल नंबर दर्ज करें',
  'auth.passwordLabel': 'पासवर्ड',
  'auth.passwordPlaceholder': 'अपना पासवर्ड दर्ज करें',
  'auth.otpLabel': 'सत्यापन ओटीपी',
  'auth.otpPlaceholder': '6 अंकों का ओटीपी दर्ज करें',
  'auth.changeMobile': 'मोबाइल नंबर बदलें',
  'auth.resendOtp': 'ओटीपी फिर भेजें',
  'auth.otpExpired': 'ओटीपी समाप्त',
  'auth.otpExpiredFull': 'ओटीपी समाप्त हो गया है। कृपया ओटीपी फिर भेजें।',
  'auth.otpExpiresIn': 'ओटीपी समाप्त होने में',
  'auth.humanPending': 'ओटीपी सत्यापन से पहले मानव सत्यापन पूरा करें।',
  'auth.humanDone': 'मानव सत्यापन पूरा हुआ।',
  'auth.sendOtp': 'ओटीपी भेजें',
  'auth.verifyOtp': 'ओटीपी सत्यापित करें',
  'menu.dashboardOverview': 'डैशबोर्ड अवलोकन',
  'menu.dashboard': 'डैशबोर्ड',
  'menu.electionManagement': 'निर्वाचन प्रबंधन',
  'menu.nagarPanchayat': 'नगर पंचायत',
  'menu.nagariNikay': 'नगरीय निकाय',
  'menu.teamAssignments': 'टीम असाइनमेंट',
  'menu.reports': 'रिपोर्ट',
  'menu.allocationReport': 'आवंटन रिपोर्ट',
  'menu.dutyAnalytics': 'ड्यूटी एनालिटिक्स',
  'menu.master': 'मास्टर',
  'menu.masterCountry': 'देश मास्टर',
  'menu.masterState': 'राज्य मास्टर',
  'menu.masterDistrict': 'जिला मास्टर',
  'menu.masterOffice': 'कार्यालय मास्टर',
  'menu.masterCity': 'शहर मास्टर',
  'menu.masterWard': 'वार्ड मास्टर',
  'menu.masterPollingStation': 'मतदान केंद्र मास्टर',
  'menu.hrms': 'एचआरएमएस',
  'menu.masterEmployee': 'कर्मचारी मास्टर',
  'menu.employeeType': 'कर्मचारी प्रकार',
  'menu.designation': 'पदनाम',
  'menu.department': 'विभाग',
  'menu.payLevel': 'पे स्केल / पे लेवल',
  'menu.employee': 'कर्मचारी',
  'menu.users': 'उपयोगकर्ता',
  'menu.accessManagement': 'एक्सेस प्रबंधन',
  'menu.authSettings': 'लॉगिन सेटिंग्स',
  'menu.districtConfig': 'जिला कॉन्फ़िगरेशन',
  'authSettings.title': 'प्रमाणीकरण सेटिंग्स',
  'authSettings.subtitle': 'लॉगिन प्रवाह, पासवर्ड आवश्यकताओं और डिफ़ॉल्ट ओटीपी बाईपास मोड को प्रबंधित करें।',
  'authSettings.defaultOtpTitle': 'डिफ़ॉल्ट ओटीपी मोड (एसएमएस बाईपास)',
  'authSettings.defaultOtpDesc': 'सक्षम होने पर, सिस्टम सभी लॉगिन के लिए "123456" का उपयोग करेगा। एसएमएस प्रदाता को बायपास किया जाता है।',
  'authSettings.passwordVerifyTitle': 'पासवर्ड सत्यापन',
  'authSettings.passwordVerifyDesc': 'सक्षम होने पर, उपयोगकर्ताओं को ओटीपी अनुरोध करने के लिए खाता पासवर्ड प्रदान करना होगा। अक्षम होने पर, केवल पंजीकृत मोबाइल से ही ओटीपी भेजा जा सकता है।',
  'authSettings.saveSuccess': 'प्रमाणीकरण सेटिंग्स सफलतापूर्वक अपडेट की गईं।',
  'authSettings.saveError': 'प्रमाणीकरण सेटिंग्स अपडेट करने में विफल।',
  'auth.defaultOtpAlert': 'ओटीपी बाईपास सक्रिय: डिफ़ॉल्ट ओटीपी है',
  'breadcrumb.home': 'होम',
  'common.create': 'बनाएं',
  'common.update': 'अपडेट करें',
  'common.save': 'सहेजें',
  'common.cancel': 'रद्द करें',
  'common.delete': 'हटाएं',
  'common.search': 'खोजें',
  'common.view': 'देखें',
  'common.status': 'स्थिति',
  'common.active': 'सक्रिय',
  'common.inactive': 'निष्क्रिय',
  'common.allStatus': 'सभी स्थितियां',
  'common.allStates': 'सभी राज्य',
  'common.allDistricts': 'सभी जिले',
  'common.allCities': 'सभी शहर',
  'common.allWards': 'सभी वार्ड',
  'common.attachment': 'अटैचमेंट',
  'common.action': 'कार्रवाई',
  'common.rows': 'पंक्तियां',
  'common.sno': 'क्र.सं.',
  'common.noRecords': 'कोई रिकॉर्ड नहीं मिला।',
  'common.loading': 'लोड हो रहा है...',
  'common.uploadLogo': 'लोगो इमेज अपलोड करें',
  'common.existingFile': 'मौजूदा फाइल यथावत रहेगी।',
  'common.deleteConfirm': 'यह रिकॉर्ड स्थायी रूप से हटाया जाएगा।',
  'masters.master': 'मास्टर',
  'masters.managePrefix': 'प्रबंधित करें',
  'masters.manageSuffix': 'मास्टर रिकॉर्ड।',
  'masters.countries': 'देश',
  'masters.country': 'देश',
  'masters.states': 'राज्य',
  'masters.state': 'राज्य',
  'masters.districts': 'जिले',
  'masters.district': 'जिला',
  'masters.offices': 'कार्यालय',
  'masters.office': 'कार्यालय',
  'masters.cities': 'शहर',
  'masters.city': 'शहर',
  'masters.wards': 'वार्ड',
  'masters.ward': 'वार्ड',
  'masters.pollingStations': 'मतदान केंद्र',
  'masters.pollingStation': 'मतदान केंद्र',
  'masters.employeeTypes': 'कर्मचारी प्रकार',
  'masters.employeeType': 'कर्मचारी प्रकार',
  'masters.designations': 'पदनाम',
  'masters.designation': 'पदनाम',
  'masters.departments': 'विभाग',
  'masters.department': 'विभाग',
  'masters.payLevels': 'पे स्केल / पे लेवल',
  'masters.payLevel': 'पे स्केल / पे लेवल',
  'masters.employees': 'कर्मचारी',
  'masters.employee': 'कर्मचारी',
  'field.name': 'नाम',
  'field.code': 'कोड',
  'field.country': 'देश',
  'field.state': 'राज्य',
  'field.district': 'जिला',
  'field.department': 'विभाग',
  'field.type': 'प्रकार',
  'field.city': 'शहर',
  'field.ward': 'वार्ड',
  'field.cityName': 'शहर का नाम',
  'field.wardNo': 'वार्ड नंबर',
  'field.wardName': 'वार्ड का नाम',
  'field.pollingStationName': 'मतदान केंद्र का नाम',
  'field.officeCode': 'कार्यालय कोड',
  'field.officeName': 'कार्यालय का नाम',
  'field.officeType': 'कार्यालय प्रकार',
  'field.parentOfficeId': 'मुख्य कार्यालय आईडी',
  'field.countryName': 'देश का नाम',
  'field.stateName': 'राज्य का नाम',
  'field.districtName': 'जिला का नाम',
  'field.districtCode': 'जिला कोड',
  'field.minAmountPay': 'न्यूनतम वेतन राशि',
  'field.maxAmountPay': 'अधिकतम वेतन राशि',
  'field.karyalayName': 'कार्यालय का नाम',
  'data.headOffice': 'मुख्य कार्यालय',
  'data.branchOffice': 'शाखा कार्यालय',
  'data.normal': 'सामान्य',
  'data.review': 'समीक्षा',
  'data.attention': 'ध्यान दें',
  'data.verified': 'सत्यापित',
  'data.pending': 'लंबित',
  'data.correction': 'सुधार',
  'data.rejected': 'अस्वीकृत',
  'data.disqualified': 'अयोग्य',
  'dashboard.liveControlRoom': 'लाइव निर्वाचन नियंत्रण कक्ष',
  'dashboard.title': 'जिला निर्वाचन डैशबोर्ड',
  'dashboard.subtitle': 'मतदाता सेवाएं, बूथ तैयारी, मतदान गतिविधि और फील्ड घटनाओं की निगरानी एक आधिकारिक कार्यक्षेत्र से करें।',
  'dashboard.registeredVoters': 'पंजीकृत मतदाता',
  'dashboard.registeredVotersCaption': '8 निर्वाचन क्षेत्रों में',
  'dashboard.pollingStations': 'मतदान केंद्र',
  'dashboard.pollingStationsCaption': '1,219 मतदान के लिए तैयार',
  'dashboard.todayTurnout': 'आज का मतदान प्रतिशत',
  'dashboard.todayTurnoutCaption': 'पिछले अपडेट से +7.4%',
  'dashboard.openIncidents': 'खुली घटनाएं',
  'dashboard.openIncidentsCaption': '4 उच्च प्राथमिकता चिह्नित',
  'dashboard.turnoutGraph': 'निर्वाचन क्षेत्र मतदान बार ग्राफ',
  'dashboard.voterPieChart': 'मतदाता सत्यापन पाई चार्ट',
  'dashboard.monitoring': 'निर्वाचन क्षेत्र निगरानी',
  'dashboard.constituency': 'निर्वाचन क्षेत्र',
  'dashboard.booths': 'बूथ',
  'dashboard.officers': 'अधिकारी',
  'dashboard.turnout': 'मतदान प्रतिशत',
  'dashboard.status': 'स्थिति',
  'dashboard.current': 'वर्तमान',
  'dashboard.operationsReadiness': 'संचालन तैयारी',
  'dashboard.priorityTasks': 'प्राथमिक कार्य',
  'dashboard.quickInsights': 'त्वरित जानकारी',
  'dashboard.serviceDesk': 'सेवा डेस्क',
  'dashboard.pollingTeam': 'मतदान टीम',
  'dashboard.lastUpdated': 'अंतिम अपडेट',
  'dashboard.boothChecklists': 'बूथ चेकलिस्ट पूर्ण',
  'dashboard.securityCompliance': 'स्ट्रॉन्ग रूम सुरक्षा अनुपालन',
  'dashboard.fieldUpdateInterval': 'औसत फील्ड अपडेट अंतराल',
  'dashboard.verificationQueue': 'मतदाता सत्यापन कतार',
  'dashboard.evmReadiness': 'ईवीएम/वीवीपैट तैयारी',
  'dashboard.officerAttendance': 'अधिकारी उपस्थिति',
  'dashboard.task1': 'लंबित बूथ अधिकारी प्रतिस्थापन स्वीकृत करें',
  'dashboard.task2': 'उच्च प्राथमिकता घटना रिपोर्ट की समीक्षा करें',
  'dashboard.task3': 'शाम 4 बजे मतदान बुलेटिन प्रकाशित करें',
  'dashboard.task4': 'स्ट्रॉन्ग रूम सुरक्षा चेकलिस्ट सत्यापित करें',
  'dashboard.helpdeskCalls': 'हेल्पडेस्क कॉल निपटाए गए',
  'dashboard.formsProcessed': 'आज प्रोसेस किए गए फॉर्म',
  'dashboard.teamsDeployed': 'तैनात टीमें',
  'dashboard.materialKits': 'तैयार सामग्री किट',
  'access.title': 'एक्सेस प्रबंधन',
  'access.subtitle': 'उपयोगकर्ता बनाएं और राज्य, जिला तथा कार्यालय एक्सेस असाइन करें।',
  'access.createUser': 'उपयोगकर्ता बनाएं',
  'access.userRecords': 'उपयोगकर्ता रिकॉर्ड',
  'access.user': 'उपयोगकर्ता',
  'access.userId': 'यूजर आईडी',
  'access.mobile': 'मोबाइल नंबर',
  'access.role': 'भूमिका',
  'access.permissions': 'अनुमतियां',
  'access.reset': 'रीसेट',
  'access.resetPassword': 'पासवर्ड रीसेट करें',
  'access.deleteUser': 'उपयोगकर्ता हटाएं',
  'access.confirmReset': 'क्या आप इस उपयोगकर्ता का पासवर्ड रीसेट करना चाहते हैं?',
  'access.confirmDelete': 'यह उपयोगकर्ता और उसकी एक्सेस अनुमतियां हटाई जाएंगी।',
  'access.stateAccess': 'राज्य एक्सेस',
  'access.countryAccess': 'देश एक्सेस',
  'access.districtAccess': 'जिला एक्सेस',
  'access.officeAccess': 'कार्यालय एक्सेस',
  'access.dragHere': 'आइटम यहां खींचें',
  'access.noRecords': 'कोई उपलब्ध रिकॉर्ड नहीं।',
  'access.errCountryFirst': 'कृपया पहले संबंधित देश चुनें।',
  'access.errStateMismatch': 'चयनित राज्य चुने गए देश के अंतर्गत नहीं आता। कृपया सही पदानुक्रम चुनें।',
  'access.errStateFirst': 'कृपया पहले संबंधित राज्य चुनें।',
  'access.errDistrictMismatch': 'चयनित जिला चुने गए राज्य के अंतर्गत नहीं आता। कृपया सही पदानुक्रम चुनें।',
  'access.errAdminState': 'कृपया सिस्टम एडमिन के लिए कम से कम एक राज्य असाइन करें।',
  'access.saveAccess': 'एक्सेस सहेजें',
  'access.sysAdminNote': 'सिस्टम एडमिन राज्य-स्तरीय है। कृपया केवल एक या अधिक राज्य असाइन करें।',
  'access.fullName': 'पूरा नाम',
  'access.email': 'ईमेल पता',
  'access.tempPassword': 'अस्थायी पासवर्ड',
  'access.selectCountry': 'देश चुनें',
  'access.selectState': 'राज्य चुनें',
  'access.selectDistrict': 'जिला चुनें',
  'access.noOffice': 'कोई कार्यालय नहीं',
  'access.address': 'पता',
  'access.saveUser': 'उपयोगकर्ता सहेजें',
  'reports.allocationTitle': 'आवंटन रिपोर्ट',
  'reports.allocationSubtitle': 'आधिकारिक ड्यूटी आदेश और तैनाती सूचियों को फिल्टर, सत्यापित और निर्यात करें।',
  'reports.exportCsv': 'CSV निर्यात करें',
  'reports.printRoster': 'रोस्टर प्रिंट करें',
  'reports.searchPlaceholder': 'बूथ या अधिकारी खोजें...',
  'reports.activeAssignments': 'सक्रिय असाइनमेंट सूची',
  'reports.officerName': 'अधिकारी का नाम',
  'reports.employeeId': 'कर्मचारी आईडी',
  'reports.stationDeployed': 'तैनात केंद्र',
  'reports.department': 'विभाग',
  'reports.contact': 'संपर्क',
  'reports.noAllocations': 'कोई आवंटन नहीं मिला।',
  'analytics.title': 'ड्यूटी एनालिटिक्स',
  'analytics.subtitle': 'दृश्य मेट्रिक्स, तैनाती दरें, छूट स्थिति और विभागीय योगदान आंकड़े।',
  'analytics.staffPool': 'कुल स्टाफ पूल',
  'analytics.activeDeployments': 'सक्रिय तैनाती',
  'analytics.exemptedStaff': 'छूट प्राप्त स्टाफ',
  'analytics.exemptionAppeals': 'छूट अपीलें',
  'analytics.deptRatios': 'विभाग तैनाती अनुपात',
  'analytics.roleStats': 'भूमिका वितरण आंकड़े',
  'analytics.proDeployed': 'पीठासीन अधिकारी (PRO) तैनात',
  'analytics.po1Deployed': 'मतदान अधिकारी 1 (PO1) तैनात',
  'analytics.po2Deployed': 'मतदान अधिकारी 2 (PO2) तैनात',
  'analytics.moDeployed': 'माइक्रो ऑब्जर्वर (MO) तैनात',
  'election.npTitle': 'नगर पंचायत डैशबोर्ड',
  'election.rnTitle': 'नगरीय निकाय डैशबोर्ड',
  'election.npSubtitle': 'नगर पंचायत निर्वाचन के वार्ड, बूथ, टीम शेड्यूल और ड्यूटी तैनाती की निगरानी करें।',
  'election.rnSubtitle': 'नगरीय निकाय निर्वाचन के वार्ड, बूथ, टीम शेड्यूल और ड्यूटी तैनाती की निगरानी करें।',
  'election.selectNpCity': 'नगर पंचायत चुनें',
  'election.selectRnCity': 'नगरीय निकाय चुनें',
  'election.allNpCities': 'सभी नगर पंचायत',
  'election.allRnCities': 'सभी नगरीय निकाय',
  'election.chooseCity': 'शहर चुनें...',
  'election.createSchedule': 'टीम शेड्यूल बनाएं',
  'election.notAssigned': 'आवंटित नहीं',
  'election.wardsScheduled': 'शेड्यूल किए गए वार्ड',
  'election.boothsScheduled': 'शेड्यूल किए गए बूथ',
  'election.teamsGenerated': 'बनी हुई टीमें',
  'election.deployedOfficers': 'तैनात अधिकारी',
  'election.applyDuty': 'ड्यूटी लागू करें',
  'election.dutyCriteria': 'ड्यूटी मानदंड',
  'election.dob': 'जन्म तिथि',
  'election.genderCond': 'लिंग शर्त',
  'election.any': 'कोई भी',
  'election.male': 'पुरुष',
  'election.female': 'महिला',
  'election.teamAssignments': 'मतदान टीम असाइनमेंट',
  'election.zonesOverview': 'निर्वाचन तैयारी अवलोकन',
  'election.timeline': 'निर्वाचन समयरेखा',
  'election.nominationStage': 'नामांकन चरण',
  'election.verificationChecks': 'सत्यापन जांच',
  'election.securityDeployed': 'सुरक्षा कर्मी तैनात',
  'election.pollingDate': 'मतदान तिथि',
  'election.open': 'खुला',
  'election.active': 'सक्रिय',
  'election.yes': 'हां',
  'election.no': 'नहीं',
  'election.selectMonitor': 'डैशबोर्ड देखने के लिए कृपया शहर चुनें।',
  'election.exemptTitle': 'कर्मचारी को असाइनमेंट से छूट दें',
  'election.exemptBtn': 'छूट दें',
  'election.searchTeam': 'टीम आईडी खोजें',
  'election.searchEmp': 'कर्मचारी आईडी/कोड खोजें',
  'election.searchIntro': 'टीम आईडी या कर्मचारी आईडी/कोड से खोजें। शहर चयन वैकल्पिक है।',
  'election.teamId': 'टीम आईडी',
  'election.stationWard': 'मतदान केंद्र / वार्ड',
  'election.noTeamRecord': 'इस टीम आईडी का कोई रिकॉर्ड नहीं मिला।',
  'election.assignMembers': 'टीम सदस्य असाइन करें',
  'election.searchEmpPlaceholder': 'कर्मचारी नाम या कोड खोजने के लिए टाइप करें...',
  'election.saveAssignments': 'असाइनमेंट सहेजें',
  'election.nominationsVerification': 'नामांकन सत्यापन',
  'election.localCandidates': 'स्थानीय उम्मीदवारों की चेकलिस्ट सत्यापन',
  'election.boothSecurity': 'मतदान केंद्र सुरक्षा',
  'election.boothSecurityDeployment': 'मतदान केंद्रों के लिए सुरक्षा कर्मियों की तैनाती जांच',
  'election.evmConfig': 'ईवीएम कॉन्फिगरेशन',
  'election.boothTestingLogs': 'बूथ आवंटन और परीक्षण लॉग सत्यापन',
  'election.enterEmpId': 'कृपया कर्मचारी आईडी या कोड दर्ज करें।',
  'election.exemptSuccess': 'कर्मचारी को सफलतापूर्वक छूट दी गई।',
  'election.exemptFailed': 'कर्मचारी को छूट देने में विफल।',
  'election.saveSuccess': 'असाइनमेंट सफलतापूर्वक सहेजे गए।',
  'election.saveFailed': 'असाइनमेंट सहेजने में विफल।',
  'election.searchTeamPlaceholder': 'उदाहरण: 0001, 0002 या 1, 2',
  'election.searchEmpPlaceholder2': 'उदाहरण: NIC001 या 123',
  'election.searchEmpPlaceholderExempt': 'कर्मचारी आईडी या कोड दर्ज करें (जैसे NIC001)',
  'election.phaseAction': 'चरण / कार्यवाही',
  'election.details': 'विवरण',
  'election.scheduleFailed': 'टीम शेड्यूल बनाने में विफल।',
  'election.applyDutyFailed': 'ड्यूटी असाइनमेंट लागू करने में विफल।',
  'election.loadingDashboard': 'डैशबोर्ड डेटा लोड हो रहा है...',
  'election.generatedNotice': 'टीम शेड्यूल पहले से उपलब्ध है।',
  'election.pollingDateValue': '15 जून 2026',
  'election.presidingOfficer': 'पीठासीन अधिकारी',
  'election.pollingOfficer1': 'मतदान अधिकारी 1',
  'election.pollingOfficer2': 'मतदान अधिकारी 2',
  'election.pollingOfficer3': 'मतदान अधिकारी 3',
  'election.pollingOfficer4': 'मतदान अधिकारी 4',
  'election.exemptReasonLabel': 'छूट का कारण',
  'election.exemptReasonPlaceholder': 'ड्यूटी से हटाने का कारण दर्ज करें...',
  'election.exemptLogsTitle': 'छूट प्राप्त कर्मचारियों का इतिहास (लॉग)',
  'election.empCode': 'कर्मचारी कोड',
  'election.empName': 'कर्मचारी का नाम',
  'election.urbanPost': 'शहरी ड्यूटी पद',
  'election.ruralPost': 'ग्रामीण ड्यूटी पद',
  'election.dateTime': 'दिनांक और समय',
  'election.exemptScopeLabel': 'छूट का दायरा (Scope)',
  'election.exemptScopeBoth': 'दोनों (शहरी और ग्रामीण)',
  'election.exemptScopeUrban': 'केवल शहरी (Urban)',
  'election.exemptScopeRural': 'केवल ग्रामीण (Rural)'
};

export default hiOverrides;
